import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, {useContext} from "react";
import AuthenticationContext from '../contexts/authentication';
import Link from 'next/link';

export default function Home() {
  const[oktaAuth,authState,name] = useContext(AuthenticationContext);
  
  const triggerSignOut = async () => {
   await  oktaAuth.signOut({  clearTokensBeforeRedirect :true ,postLogoutRedirectUri: 'http://localhost:3000/',});
  }

 const triggerLogin = async () => {
   oktaAuth.signInWithRedirect({ originalUri: '/' });
  }

  const handleRedirect =  async () => {
      await oktaAuth.handleLoginRedirect({originalUri: 'http://localhost:3000/'});
  }
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Personicle</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className={styles.main}>
       {!authState && (
          <>
          Not signed in <br /> 
          <button onClick={triggerLogin}>Sign In With Okta</button> 
          
          </>
        )}
      {authState && (
          <>
          Welcome to the super awesome personicle {name} <br /> 
          
          <button onClick={triggerSignOut}>Sign Out </button> 
          <button>
            <Link href="/data-connections">To the connections</Link>
          </button>
        
          </>
        )}

      </main>
    </div>
  )
}
