import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, {useContext} from "react";
import AuthenticationContext from '../contexts/authentication';
import Link from 'next/link';
import {OktaSignIn} from '@okta/okta-signin-widget';
export default function Home() {
  const[oktaAuth,authState,name] = useContext(AuthenticationContext);
  var oktaSignIn = new OktaSignIn({
    baseUrl: orgUrl,
    clientId: 'smBXcoabniBOUsja0A6b7', 
    redirectUri: 'http://localhost:3000',
    authParams: {
      issuer: 'default', 
      responseType: 'id_token',
      scopes: ['openid', 'email','profile'],
    },
    idps:[
      { type: 'google', id: '0oadrrh812O9sbabE0h7' },
    ],
    idpDisplay: "PRIMARY",
    // i18n: {
    //   en: {
    //     'password.forgot.email.or.username.placeholder': 'Email',
    //     'password.forgot.email.or.username.tooltip': 'Email',
    //     'errors.E0000095': 'Unable to reset password.  Did you put in a valid email?'
    //   }
    // }
  });
  const triggerSignOut = async () => {
   await  oktaAuth.signOut({  clearTokensBeforeRedirect :true ,postLogoutRedirectUri: 'http://localhost:3000/',});
  }

 const triggerLogin = async () => {
   oktaAuth.signInWithRedirect({ originalUri: '/' });
  }
  // const triggerGoogleLogin = async => {
  //   oktaSignIn.signInWithRedirect({}  )
  // }
  const handleRedirect =  async () => {
      await oktaAuth.handleLoginRedirect({originalUri: 'http://localhost:3000/'});
  }
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Personicle</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className={styles.main}>
       {!authState && (
          <>
          Not signed in <br /> 
          <button onClick={triggerLogin}>Sign In With Okta</button> 
          <button>
          <a href="https://dev-01936861.okta.com/oauth2/v1/authorize?idp=0oa3v658b8VCLoy3L5d7&client_id=0oa3sq0q2iDDS2IV25d7&response_type=id_token&response_mode=fragment&scope=openid%20email&redirect_uri=http://localhost:3000&state=WMffre6D&nonce=YsGfre76jo">Sign in with Google</a>
         </button>
          </>
        )}
      {authState && (
          <>
          Welcome to the super awesome personicle {name} <br /> 
          
          <button onClick={triggerSignOut}>Sign Out </button> 
          <button>
            <Link href="/data-connections">To the connections</Link>
          </button>
        
          </>
        )}

      </main>
    </div>
  )
}
