import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, {useContext,useEffect,useState} from "react";
import AuthenticationContext from '../contexts/authentication';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import config from './config';
import { useRouter } from 'next/router';


export default function Home() {
  const[oktaAuth,authState,name] = useContext(AuthenticationContext);

  const googleAuthorizeRoute = "https://dev-01936861.okta.com/oauth2/v1/authorize?idp="+config.idps.googleId+'&client_id='+config.oidc.clientId+'&response_type=code%20token%20id_token&response_mode=fragment&scope=openid%20email%20profile&redirect_uri='+config.idps.redirect_uri+'&state='+config.idps.state+'&nonce='+config.idps.nonce;
  const triggerSignOut = async () => {
   await  oktaAuth.signOut({  clearTokensBeforeRedirect :true ,postLogoutRedirectUri: 'http://localhost:3000/',});
  }

 const triggerLogin = async () => {
   oktaAuth.signInWithRedirect({ originalUri: '/' });
  }
  
  const handleRedirect =  async () => {
      await oktaAuth.handleLoginRedirect({originalUri: 'http://localhost:3000/'});
  }
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Personicle</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className={styles.main}>
       {!authState && (
          <>
          Not signed in <br /> 
          <button onClick={triggerLogin}>Sign In With Okta</button> 
          {/* <button>
              <Link href={googleAuthorizeRoute}>Sign In With Google</Link>
          </button> */}
           
            <div ></div>
      
          </>
        )}
      {authState && (
          <>
          Welcome to the super awesome personicle {name} <br /> 
          
          <button onClick={triggerSignOut}>Sign Out </button> 
         
          <button>
            <Link href="/testPage">To the connections</Link>
          </button>
        
          </>
        )}

      </main>
    </div>
  )
}
