import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from "react";
import Link from "next/link";
import { useSession } from 'next-auth/client';
import DataConnectionsDiv from "../reactComponents/DataConnections"
import TimelineChart from "../reactComponents/TimelineChart"
import BarChart from "../reactComponents/BarChart"
import useGoogleCharts from '../reactComponents/useGoogleCharts'
import ProgressionChart from '../reactComponents/ProgressionChart';

// const ingestionServer = "https://20.121.8.101:8000"
// const ingestionServer = "https://127.0.0.1:5000"
// const ingestionServer = "https://personicle-data-ingestion.azurewebsites.net"

const userConnections = [
    {
        'source': 'FitBit',
        'icon': '',
        'redirect': ingestionServer + '/fitbit/connection',
        'return': 'http://localhost:3000/testPage'
        // process.env.AUTH_SERVER + ':' + process.env.AUTH_PORT + process.env.FITBIT_AUTH_ENDPOINT
    },
    {
        'source': 'Oura',
        'icon': '',
        'redirect': '/',
        'return': 'http://localhost:3000/testPage'
    },
    {
        'source': 'GoogleFit',
        'icon': '',
        'redirect': ingestionServer + '/google-fit/connection',
        'return': 'http://localhost:3000/testPage'
    }
]

export default function TestPage(){
    const [session, loading] = useSession();
    const google = useGoogleCharts();

    return(
        <div className={styles.container}>
            <Head>
                <title>Personicle</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <div className={styles.Row}>
                    <div className={styles.Column}><DataConnectionsDiv sources={userConnections}/></div>
                    {/* <div className={styles.Column}><TimelineChart google={google}/></div> */}
                    {/* <div className={styles.Column}><BarChart google={google}/></div> */}
                    {/* <div className={styles.Column}><MyComponent google={google}/></div> */}
                    {/* <div className={styles.Column}>Summary View Tab</div> */}
                    <div className={styles.Column}><ProgressionChart google={google}/></div>
                </div>
            </main>

        </div>
        
    );
}